# Site
name: 'Capital Stance'

title: 'Capital Stance'

description: 'Capitalstance delivers and offers advice, insight, profiles and guides in financial matters to make you master every aspect to make a sound financial decision.'

logo: 'assets/images/logo.png'

favicon: 'assets/images/favicon.png'

baseurl: ""

disqus: 

email: 'https://formsubmit.co/insight@capitalstance.com'
#mailchimp-list: 'https://formsubmit.co/insight@capitalstance.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-include-cache

  
#authors:
  #  sal:
  #    name:           Sal
  #    site:           https://www.wowthemes.net
  #    avatar:         /assets/images/avatar1.jpg
  #    bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
  #    email:          wowthemesnet@gmail.com
  #    twitter:        https://twitter.com/wowthemesnet

  #  jane:
  #    name:           Jane
  #    site:           https://www.wowthemes.net
  #    avatar:         /assets/images/avatar2.jpg
  #    bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
  #    email:          fakemail@gmail.com
  #    twitter:        https://twitter.com/wowthemesnet
      
      
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


###########

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-YEPLV6S039

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "" 

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  
 ########## 


# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

remote_theme: 'wowthemesnet/mundana-theme-jekyll'
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one





# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
