name: Schedule Posts

on:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow every day at midnight UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Install Jekyll
        run: gem install jekyll bundler

      - name: Install dependencies
        run: bundle install

      - name: Build and deploy site
        run: bundle exec jekyll build --future

      - name: Push changes to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_posts
